# Generated by Django 5.0 on 2023-12-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_customer_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
    ]
