# Generated by Django 5.0 on 2023-12-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
    ]
