# Generated by Django 5.0 on 2023-12-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_orderitem_order_products_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
