# Generated by Django 5.0 on 2025-01-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_replay_user_remove_comment_product_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='containsNotConfirmedComments',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
