# Generated by Django 5.0 on 2025-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='isInSlider',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
