# Generated by Django 5.0 on 2023-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('priority', models.CharField(blank=True, choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'The Question',
                'verbose_name_plural': 'The Questions',
            },
        ),
    ]
