# Generated by Django 5.0 on 2023-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, max_length=400, null=True)),
                ('answer', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
