# Generated by Django 5.0 on 2023-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='number',
        ),
        migrations.AddField(
            model_name='faqs',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
