# Generated by Django 5.0 on 2023-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_faqs_number_faqs_auto_increment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='faqs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
