# Generated by Django 5.0 on 2023-12-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_delete_about_remove_faqs_auto_increment_id_faqs_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
    ]
